### ISSUE TITLE
Dialogs not interactive in Houdini

### ISSUE THREAD

**Issue by mruegenberg** [Colorbleed/qtazu#9]
When following the READMe for e.g the login widget, using the `show()` method, the widget is shown but does not appear to be interactive (ie typing into the fields doesn't work).

As the widgets are `QDialog`s, running e.g `login.exec_()` might be more correct?

This is using Houdini 19.5 (with Python 3).

**Comment by BigRoy** [comment]
Interesting. Them not being interactive sounds like there's no running QApplication instance. Are you sure you are not getting other errors by any chance?

> As the widgets are QDialogs, running e.g login.exec_() might be more correct?

Not necessarily. Running `exec_()` would just ensure they'd run as a modal dialog as far as I know which isn't always what you'd want.

**Comment by mruegenberg** [comment]
I had another look and found a solution. 

Two things need to be done for the sample code to work in Houdini:

- pass the Houdini window as a parent to the widget's constructor
- the code does not work in a Python shell, so must be added e.g in a shelf tool, see [here](https://www.sidefx.com/docs/houdini/hom/cb/qt.html)

So, a working sample approach would be:

Create a new Houdini shelf tool and set its (Python) code to

~~~
# if experimenting with Qtazu and you have it in a venv somewhere, add it to the python path:
# import sys
# sys.path.append('path-to-venv/lib/python3.9/site-packages')

from qtazu.widgets.login import Login
import hou # usually not needed

widget = Login(hou.qt.mainQtWindow())
widget.show()
~~~

Note this is actually not Qtazu-specific - testing with pure PySide test code shows the same behaviour.

**Comment by BigRoy** [comment]
Thanks, in that case I think the shelf button would've helped sufficiently and you don't need to parent it to Houdini's main window aside of potentially persisting the variables outside of the current shelf script scope (otherwise it'd get garbage collected and likely would instantly disappear as soon as it gets shown).

Anyway, thanks for following up.

**Comment by mruegenberg** [comment]
Yep, I can confirm that actually the parenting was not necessary
Thanks for checking!
